name: Publish Edge Add-on
author: hyperbola
description: Publish addon onto Edge Add-ons

inputs:
  product-id:
    description: Product ID of the add-on.
    required: false
  zip-path:
    description: Path to the zip file of the add-on.
    required: false
  api-key:
    description: Edge publish API key.
    required: true
  client-id:
    description: Edge publish API client ID.
    required: true
  upload-only:
    description: Upload the extension without publishing. Default to false.
    required: false
    default: "false"

runs:
  using: node20
  main: index.cjs

branding:
  icon: aperture
  color: blue
